### ISSUE TITLE
Unicode file names are not supported (even though they work when uploading through GitHub UI)

### ISSUE THREAD

**Issue by PhilipRoman** [skx/github-action-publish-binaries#18]
This is not a critical issue as it can be easily fixed, but I just wanted to let you know in case if anyone else encounters this problem.

If the uploaded file name contains a non-ascii character, I get the following output:
```
Run skx/github-action-publish-binaries@master
/usr/bin/docker run ...
Processing file ./build/Klavietūra.zip
Upload URL is https://uploads.github.com/repos/PhilipRoman/***/releases/***/assets?name=Klavietūra.zip
***************************
 upload was not successful.
 Aborting
 HTTP status is 400
**********************************
<!DOCTYPE html><title>Malformed request</title>
<body>We didn't receive a proper request from your browser. Please contact us if the problem persists.</body>
</html>
##[error]Docker run failed with exit code 1
```

Changing the file name to avoid non-ascii characters fixed the issue.

**Comment by skx** [comment]
Thanks for the notification; I guess it is hard to see where the issue is:

* Is it the curl command that needs quoting, or special handling.
* Or does the Github API just reject it?

Have you (manually) uploaded assets with non-ASCII names in the past, via their upload form?  (I admit I never have; I speak a tiny bit of Finnish but all my assets are English as that's my native language!)

**Comment by PhilipRoman** [comment]
It appears that GitHub has recently changed something - I know for a fact that somewhere around end of 2019 our release files had non-ascii filenames. Now GitHub transliterates all characters to the ascii set.
