### ISSUE TITLE
Error when upload

### ISSUE THREAD

**Issue by hmuschett** [skx/github-action-publish-binaries#26]
Hi Im trying  to use action but a I have a error can you help me 
this is my config 
`jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout the repository
      uses: actions/checkout@v2
   

    - name: Generate build files
      uses: thatisuday/go-cross-build@v1.1.0
      with:
          platforms: 'linux/amd64'
          package: ''
          name: 'app'
          compress: 'false'
          dest: 'dist'

      # step 3: Copy build-artifacts in the GitHub release
    - name: Copy build-artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: "./dist/*"
        `
and i have this error 

Arguments : ./dist/*
Release ID: 
Discovered RELEASE_ID: null
Processing file ./dist/app-linux-amd64
Upload URL is https://uploads.github.com/repos/hmuschett/victoryDash/releases/null/assets?name=app-linux-amd64
***************************
 upload was not successful.
 Aborting
 HTTP status is 404
**********************************
{"message":"Not Found","request_id":"07C0:9B5F:177416:1B8A7D:5FC7B6C7","documentation_url":"https://docs.github.com/rest"}

**Comment by skx** [comment]
* The action is triggered by a release event.
* The action should attach your binaries to that release.

Since you're not running on a release event there's nothing to attach the result(s) to, so it fails.

You should resolve this by making your action only run `on: release:`

That way:

* The release will be made.
* The action will trigger.
* It will determine the release event which triggered it.
* It will attach the binaries.

If you wish to _create_ a release, via github actions, then you need to explicitly add a create-release step appropriately.
